sources:
  include:
    - ../../Seventwos
    - ../../NSE
  exclude:
    - ../../Seventwos/Sources/Mocks/SDK
templates:
  - AutoMockable.stencil
output:
  ../../Seventwos/Sources/Mocks/Generated/GeneratedMocks.swift
