input_dir: ../../Seventwos/
output_dir: ../../Seventwos/Sources/Generated/
xcassets:
  inputs:
    - Resources/Assets.xcassets
  outputs:
    templateName: swift5
    output: Assets.swift
strings:
  - inputs: Resources/Localizations/en.lproj
    filter: Localizable*
    outputs:
      templatePath: Templates/Strings/structured-swift5-seventwos.stencil
      output: Strings.swift
      params:
        enumName: L10n
        lookupFunction: tr  # used for the loc to be computed variables
        publicAccess: false
  - inputs: Resources/Localizations/en.lproj
    filter: Untranslated*
    outputs:
      templatePath: Templates/Strings/structured-swift5-seventwos-untranslated.stencil
      output: Strings+Untranslated.swift
      params:
        enumName: UntranslatedL10n
        lookupFunction: tr  # used for the loc to be computed variables
        publicAccess: false
